### ISSUE TITLE
Google Maps JavaScript API warning: SensorNotRequired

### ISSUE THREAD

**Issue by CecileBr** [WordPressUtilities/wpugmapsautocompletebox#3]
Hi @Darklg,

While using the plugin, I've noticed a warning from Google Maps API

> Google Maps JavaScript API warning: SensorNotRequired [https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required](https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required)

It refers to the line below (311)
``` php
wp_enqueue_script('wpugmapsabox-maps', 'https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places&key=' . $this->frontapi_key . '&language=' . $this->mainlang . '&sensor=false', false, '3.exp', true);
```

I can make a PR request if needed!

**Comment by Darklg** [comment]
@CecileBr so sorry i did not see your issue earlier ! 

I pushed a fix in the latest release : https://github.com/WordPressUtilities/wpugmapsautocompletebox/releases/tag/0.17.1

Thanks again for the tip !

**Comment by CecileBr** [comment]
Oh, I had forgotten about it!

Thanks
